//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        public int id { get; set; }
        [Display(Name ="User Name")]
        [Required(ErrorMessage = "required")]
        public string username { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
         @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
         @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",ErrorMessage ="Invalid Email")]
        public string email { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage ="required")]
        [DataType(DataType.Password)]
        public string password { get; set; }


        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage ="required")]
        [DataType(DataType.Password)]
        [Compare("password",ErrorMessage = "Password is not Identical")]
        public string Confirm_password { get; set; }

    }
}
