//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Orders = new HashSet<Order>();
            this.Purchasings = new HashSet<Purchasing>();
        }
    
        [Key]
        public int med_id { get; set; }
       
        [Display(Name = "Medicine Name")]
        [Required]
        public string name { get; set; }

        [Display(Name = "Medicine Type")]
        [Required]
        public string type { get; set; }

        [Display(Name = "Price")]
        [Required]
        public Nullable<double> price { get; set; }

        [Display(Name = "Quantity")]
        [Required]
        public Nullable<int> quantity { get; set; }

        [Display(Name = "Total")]
        [Required]
        public Nullable<double> total { get; set; }
        public int cat_id { get; set; }
        public int sup_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchasing> Purchasings { get; set; }
    }
}
