//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Reports = new HashSet<Report>();
        }
    
        [Key]
        public int ord_id { get; set; }

        [Display(Name ="Order Detail")]
        [Required]
        public string ord_detail { get; set; }
        [Display(Name = "Date")]
        [Required]

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date_of_order { get; set; }

        [Display(Name = "Customer ID")]
        public Nullable<int> cus_id { get; set; }

        [Display(Name = "Price")]
        [Required]
        public Nullable<double> unit_price { get; set; }

        [Display(Name = "Quantity")]
        [Required]
        public Nullable<int> quantity { get; set; }

        [Display(Name = "Total")]

        public Nullable<double> total { get; set; }

        [Display(Name = "Medicine ID")]

        public Nullable<int> med_id { get; set; }

        [Display(Name = "Purchase ID")]
        public Nullable<int> pur_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Medicine Medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
