//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        [Key]
        public int staf_id { get; set; }

        [Display(Name = "First Name")]
        [Required]

        public string firstname { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        public string lastname { get; set; }

        [Display(Name = "Gender")]
        [Required]

        public string gender { get; set; }

        [Display(Name = "Address")]
        [Required]


        public string address { get; set; }

        [Display(Name = "Phone")]
        [Required]


        public string phone { get; set; }

        [Display(Name = "Email")]
        [Required]
        [EmailAddress]


        public string email { get; set; }

        [Display(Name = "UserName")]
        [Required]

        public string username { get; set; }

        [Display(Name = "Password")]
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Required]
        public int role_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Role Role { get; set; }
    }
}
